### ISSUE TITLE
PKG_CONFIG_PATH may not be set

### ISSUE THREAD

**Issue by utke1** [bradbell/cmpad#1]
https://github.com/bradbell/cmpad/blob/8e4c0502c6b33d3fefe92df417fd88e1c0c424d9/cpp/bin/get_package.sh#L104

On all of my ubunut VMs, even though I have the pkg-config installed that variable isn't set so I am getting:
```
cpp/bin/get_package.sh: line 104: PKG_CONFIG_PATH: unbound variable
```

**Comment by bradbell** [comment]
You are correct. I will fix this. 
Thanks !!

For the moment, you could define and export and empty PKG_CONFIG_PATH before calling  get_package.sh. I think that will work.

**Comment by bradbell** [comment]
I think I have fixed this with the commit
https://github.com/bradbell/cmpad/commit/f3e8efa83a6752fc6108d2cb9a70e0a694a81820

If this works for you please close this issue

**Comment by utke1** [comment]
yes, works for me
