### ISSUE TITLE
confused about the logic in fun_speed 

### ISSUE THREAD

**Issue by utke1** [bradbell/cmpad#12]
https://github.com/bradbell/cmpad/blob/d8508ab941f119e74105b164139408708a30e9c4/python/cmpad/fun_speed.py#L89C4-L95C30

The lines referenced above - when I step through with the debugger line by line it happens slow enough so that ```t_diff```  is big enough and in the debugger I never enter the while loop .  So the question why do you call before the while loop default timer to set start and end and compute the diff instead of not invoking the default timer and simply setting ```t_diff=0``` ?

**Comment by bradbell** [comment]
See fun_peed.py in  commit
https://github.com/bradbell/cmpad/commit/3febdb224223cf3bfbd7213b10fd8da154255d07

Please close this issue if you are satisfied with the commit above.

**Comment by utke1** [comment]
yes, thanks
