### ISSUE TITLE
confusion between  bin/get_package.sh and  cpp/bin/get_package.sh  ?

### ISSUE THREAD

**Issue by utke1** [bradbell/cmpad#3]
the documentation references both locations... e.g confusingly  https://github.com/bradbell/cmpad/blob/8e4c0502c6b33d3fefe92df417fd88e1c0c424d9/bin/get_package.sh#L26

i.e. the reference to ```cpp/bin/get_package.sh``` from within ```bin/get_package.sh```  which one is authoritative?

**Comment by bradbell** [comment]
I need to clean the documentation up some so that it is more explicit). 
I use cmpad.git for the top source directory. The documentation in cmpad.git/bin/get_package.sh is for
`bin/get_package.sh` not for `cpp/bin /get_package.sh` or `bin/python/get_package.sh`.

Does this help ?

**Comment by bradbell** [comment]
See the heading 09-21 on
https://cmpad.readthedocs.io/2024.html#mm-dd-09-21

Please close this issue if you are satisfied with the result.

**Comment by bradbell** [comment]
@utke1 Thank you for helping make this project better !!
